function  robot = threeLink

persistent memory;

if length(memory) ~= 0
  robot = memory;
  return
end

% This robot is implemented as a 3-link chain with 3 revolute joints,
% but the joints are subject to the constraint q(2)==q(3).

color.lightblue = [176 196 222]/255;
color.darkblue = [70 130 180]/255;

function axislines = drawaxis(size, radius)
   axislines = {
   'colour', [1 0 0] , ...
   'cyl', [0 0 0; size 0 0], radius, ...
   'colour', [0 1 0] , ...
   'cyl', [0 0 0; 0 size 0], radius, ...
   'colour', [0 0 1] , ...
   'cyl', [0 0 0; 0 0 size], radius};
end

m = 9.375;
w = 0.05;
l = 0.5;
Ilink = mcI( m, [0 0 -l/2], (m/12)*diag([(w^2+l^2) (w^2+l^2) (w^2+w^2)]));

robot.NB = 3;
robot.parent = [0 1 2];
robot.jtype = {'Rx', 'Rx', 'Rx'};
robot.Xtree = {jcalc('Rx',0), rotx(0)*xlt([0 0 -l]), rotx(0)*xlt([0 0 -l])};
robot.gravity = [0 0 -9.81];	
robot.I = {Ilink, Ilink, Ilink} ;

robot.appearance.body{1} = ...
    { drawaxis(0.25,0.01), ...
      'colour', color.lightblue, ...
      'box', [w/2 w/2 0; -w/2 -w/2 -l], ...
      'colour', color.lightblue, ...
      'cyl', [w/2 0 0; -w/2 0 0], 0.035, ...
      'colour', color.lightblue, ...
      'cyl', [w/2 0 -l; -w/2 0 -l], 0.035, ...
       };
  
robot.appearance.body{2} = ...
    { drawaxis(0.25,0.01), ...
      'colour', color.darkblue, ...
      'box', [w/2 w/2 0; -w/2 -w/2 -l], ...
      'colour', color.darkblue, ...
      'cyl', [w/2 0 0; -w/2 0 0], 0.035, ...
      'colour', color.darkblue, ...
      'cyl', [w/2 0 -l; -w/2 0 -l], 0.035, ...
      };
  
robot.appearance.body{3} = ...
    { drawaxis(0.25,0.01), ...
      'colour', color.lightblue, ...
      'box', [w/2 w/2 0; -w/2 -w/2 -l], ...
      'colour', color.lightblue, ...
      'cyl', [w/2 0 0; -w/2 0 0], 0.035, ...
      'colour', color.lightblue, ...
      'cyl', [w/2 0 -l; -w/2 0 -l], 0.035, ...
      };
  
end
